site_name: CloudStream 插件文档
site_description: 插件说明与下载
site_url: https://<username>.github.io/<repo>

nav:
  - 使用指南: index.md
  - 开发指南: guide.md
  - CloudStream分析: cloudstream_analysis.md
  - TVBox分析: tvbox_analysis.md
  - API知识: dev.md
  - 广告过滤器使用文档: ad_filter_guide.md
  - 广告过滤器开发文档: ad_filter_dev.md
  - 解析播放开发文档: vip_parser_dev.md

theme:
  name: material
  language: zh

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - admonition
  - footnotes
  - def_list
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences
